# Generated by Django 5.1.6 on 2025-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tun_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecord",
            name="period_type",
            field=models.CharField(default="公历", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userrecord",
            name="reminder_threshold",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
    ]
